/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/main': RouteRecordInfo<'/main', '/main', Record<never, never>, Record<never, never>>,
    '/main/github-sign/': RouteRecordInfo<'/main/github-sign/', '/main/github-sign', Record<never, never>, Record<never, never>>,
    '/main/keep-alive1/': RouteRecordInfo<'/main/keep-alive1/', '/main/keep-alive1', Record<never, never>, Record<never, never>>,
    '/main/keep-alive2/': RouteRecordInfo<'/main/keep-alive2/', '/main/keep-alive2', Record<never, never>, Record<never, never>>,
    '/main/keep-alive3/': RouteRecordInfo<'/main/keep-alive3/', '/main/keep-alive3', Record<never, never>, Record<never, never>>,
  }
}
