/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/main': RouteRecordInfo<'/main', '/main', Record<never, never>, Record<never, never>>,
    '/main/app-icon/': RouteRecordInfo<'/main/app-icon/', '/main/app-icon', Record<never, never>, Record<never, never>>,
    '/main/app-icon(requestAnimationFrame)/': RouteRecordInfo<'/main/app-icon(requestAnimationFrame)/', '/main/app-icon(requestAnimationFrame)', Record<never, never>, Record<never, never>>,
    '/main/github-sign/': RouteRecordInfo<'/main/github-sign/', '/main/github-sign', Record<never, never>, Record<never, never>>,
    '/main/horizontal-waterfall/': RouteRecordInfo<'/main/horizontal-waterfall/', '/main/horizontal-waterfall', Record<never, never>, Record<never, never>>,
    '/main/intersection-observer/': RouteRecordInfo<'/main/intersection-observer/', '/main/intersection-observer', Record<never, never>, Record<never, never>>,
    '/main/loading/': RouteRecordInfo<'/main/loading/', '/main/loading', Record<never, never>, Record<never, never>>,
    '/main/luminescence/': RouteRecordInfo<'/main/luminescence/', '/main/luminescence', Record<never, never>, Record<never, never>>,
    '/main/mind/': RouteRecordInfo<'/main/mind/', '/main/mind', Record<never, never>, Record<never, never>>,
    '/main/mind/vue-shape/dropdown': RouteRecordInfo<'/main/mind/vue-shape/dropdown', '/main/mind/vue-shape/dropdown', Record<never, never>, Record<never, never>>,
    '/main/rsa/': RouteRecordInfo<'/main/rsa/', '/main/rsa', Record<never, never>, Record<never, never>>,
    '/main/test/': RouteRecordInfo<'/main/test/', '/main/test', Record<never, never>, Record<never, never>>,
  }
}
